# MySQL.  Versions 5.0+ are recommended.
development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: student_management
  pool: 5
  username: root
  host: localhost

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: student_managements
  pool: 5
  username: root
  host: localhost

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: student_production
  pool: 5
  username: root
  host: localhost
